from django.urls import path
from loan_app.views import (
    loan_step, 
    loan_success, 
    home, 
    about, 
    contact, 
    privacy_policies, 
    terms_and_conditions, 
    submit_tips_email, 
    check_status_view, 
    business_expense_loan, 
    debt_consolidation_loan, 
    education_cost_loan, 
    emergency_expense_loan, 
    home_improvement_loan, 
    one_of_purchase_loan, 
    personal_expense_loan, 
    travel_expense_loan,
    vehicle_expense_loan,
    wedding_event_loan,
)

urlpatterns = [
    path("loan/step/<int:step>/", loan_step, name="loan_step"),
    path("loan/success/", loan_success, name="loan_success"),
    path("", home, name="home"),
    path("loan/about/", about, name="about"),
    path("loan/contact/", contact, name="contact"),
    path("loan/privacy_policies/", privacy_policies, name="privacy_policies"),
    path("loan/terms_and_conditions/", terms_and_conditions, name="terms_and_conditions"),
    path("subscribe/", submit_tips_email, name="submit_tips_email"),
    path('loan/check_status/', check_status_view, name='check_status'),
    path('loan/service/business_expense_loan', business_expense_loan, name='business_expense_loan'),
    path('loan/service/debt_consolidation_loan', debt_consolidation_loan, name='debt_consolidation_loan'),
    path('loan/service/education_cost_loan', education_cost_loan, name='education_cost_loan'),
    path('loan/service/emergency_expense_loan', emergency_expense_loan, name='emergency_expense_loan'),
    path('loan/service/home_improvement_loan', home_improvement_loan, name='home_improvement_loan'),
    path('loan/service/one_of_purchase_loan', one_of_purchase_loan, name='one_of_purchase_loan'),
    path('loan/service/personal_expense_loan', personal_expense_loan, name='personal_expense_loan'),
    path('loan/service/travel_expense_loan', travel_expense_loan, name='travel_expense_loan'),
    path('loan/service/vehicle_expense_loan', vehicle_expense_loan, name='vehicle_expense_loan'),
    path('loan/service/wedding_event_loan', wedding_event_loan, name='wedding_event_loan'),
]
