# Generated by Django 4.2.21 on 2025-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_alter_loanapplications_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
