# Generated by Django 4.2.21 on 2025-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_updatetips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplications',
            old_name='house_name',
            new_name='house_number',
        ),
        migrations.AlterField(
            model_name='loanapplications',
            name='employement_status',
            field=models.CharField(blank=True, choices=[('full', 'Full Time Employed'), ('self', 'Self Employed'), ('part', 'Part Time Employed'), ('retired', 'Retired'), ('benefits', 'Benefits'), ('unemployed', 'Unemployed')], max_length=50, null=True),
        ),
    ]
