# Generated by Django 4.2.21 on 2025-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_rename_house_name_loanapplications_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplications',
            name='monthly_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='year_of_employement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
