# Generated by Django 4.2.21 on 2025-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_loanapplications_monthly_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplications',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
