# Generated by Django 4.2.21 on 2025-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_loanapplications_accepted_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplications',
            name='accepted_terms',
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='provide_bank_details',
            field=models.BooleanField(default=True),
        ),
    ]
